# Generated by Django 5.1.2 on 2024-11-26 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='usermovie',
            name='user',
        ),
        migrations.AddField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_users', to='main.movie'),
        ),
        migrations.AddField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
